# Generated by Django 3.1.3 on 2021-09-02 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashBoard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fundraiser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_name', models.CharField(max_length=200)),
                ('campaign_url', models.SlugField(max_length=250)),
                ('patient_name', models.CharField(max_length=250)),
                ('relation_to_patient', models.CharField(max_length=250)),
                ('patient_rel_name', models.CharField(max_length=240)),
                ('campaign_description', models.TextField()),
                ('amount_needed', models.FloatField()),
                ('amount_raised', models.FloatField(default=0)),
                ('video_url', models.URLField(max_length=250, unique=True)),
                ('completed', models.BooleanField(default=False)),
                ('soft_delete', models.BooleanField(default=True)),
                ('ending_title', models.CharField(blank=True, max_length=250, null=True)),
                ('ending_description', models.TextField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashBoard.donor')),
            ],
        ),
        migrations.CreateModel(
            name='Photos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='')),
                ('pic_or_doc', models.BooleanField(default=False)),
                ('fundraiser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashBoard.fundraiser')),
            ],
        ),
    ]
