# Generated by Django 3.1.3 on 2021-09-02 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashBoard', '0002_fundraiser_photos'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundraiser',
            name='campaign_photo',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
