# Generated by Django 3.1.3 on 2021-09-02 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashBoard', '0003_fundraiser_campaign_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundraiser',
            name='campaign_url',
            field=models.SlugField(blank=True, max_length=250),
        ),
    ]
