# Generated by Django 3.1.3 on 2021-09-02 08:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashBoard', '0008_fundraiser_start_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fundraiser',
            name='owner',
        ),
        migrations.AlterField(
            model_name='fundraiser',
            name='phone_number',
            field=models.CharField(max_length=17, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
