# Generated by Django 3.1.3 on 2021-09-02 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashBoard', '0009_auto_20210902_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundraiser',
            name='email',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='fundraiser',
            name='campaign_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
