# Generated by Django 3.1.3 on 2021-09-02 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashBoard', '0010_auto_20210902_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundraiser',
            name='email',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
