# Generated by Django 3.1.3 on 2021-09-03 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashBoard', '0015_auto_20210903_0152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fundraiser',
            name='campaign_photo',
        ),
    ]
