# Generated by Django 3.1.3 on 2021-09-05 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashBoard', '0019_payments'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payments',
        ),
    ]
